[FEATURE] 리프레쉬토큰 기능 구현 #126
TeamSodam/sodam-server pull request #164
Opened 2022-05-29 16:43 UTC by choiyoorim

## ✅ PR check list

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message가 적절한지 확인해주세요.
- [x] 적절한 branch로 요청했는지 확인해주세요.
- [x] Assignees, Label을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.

<br/>

## 📝 PR 요약

- 리프레쉬 토큰 기능을 위해 레디스 서버와 연동 작업
- 리프레쉬 토큰 발급 기능(로그인, 회원가입시 자동으로 리프레쉬 토큰 발급)
- 어세스 토큰이 만료되면 리프레쉬 토큰을 통해 새로운 어세스 토큰을 발급
- resolved: #126 

<br/>

## 📌 변경 사항 및 주의 사항
테스트 전에 npm i 한번씩 진행 후 테스트해주세요! (여러가지 새로운 패키지들을 설치함)
그리고 전체적인 리프레쉬 토큰 발급 과정의 흐름을 봐주시면 감사하겠습니다. 제가 놓친 분기 처리 부분이 있을 것 같아서...
또한 api 명세서와 한번씩 비교하면서 작업했으나 api 명세서와는 달라진 부분들이 있어서 웹에게 문의 후 api 명세서 변경 진행해야 할듯합니다.
그래서 한번씩 response 부분에 집중해서 봐주시면 좋을 것 같아요! 
특히 cookie에 userId와 refreshtoken을 따로 인덱스,값 이런식으로 전달하고 있는데 이게 옳은 방법인지 잘 모르겠습니다...
그리고 서버와 연결이 잘 되는지.. 테스트해주시면 감사합니다.
제가 작성할 때는 잘 되는데 다른 사람 컴퓨터에서도 잘 되는지 확인해보고 싶어서요!

<br/>

2022-05-30 08:54 UTC, LeeJE20 requested changes
코멘트

2022-05-30 08:54 UTC, LeeJE20 commented on src/routes/auth/authLoginPOST.js
> +const userImageDELETE = require('../user/userImageDELETE');
이 라인 실수로 들어간 것 같아요!!

2022-05-30 08:54 UTC, LeeJE20 commented on src/routes/auth/authLoginPOST.js
> +const { stringify } = require('yamljs');
이 라인 실수로 들어간 것 같아요!!

2022-05-30 08:54 UTC, LeeJE20 commented on src/routes/auth/authLoginPOST.js
>      if (user.length !== 0) {
혹시 24번 라인에 오류 안 생기나요??
이 코드 윗 부분에 user라는 변수를 생성하는 내용이 없는 것 같아서 물어봐요!
덧붙여서 user가 undefind일 경우, user.length를 불러오는 과정에서 오류가 날 수 있으므로 24번줄의 if문을 `if (user && user.length !== 0)` 이런 식으로 user가 undefined가 아닌지 검증하는 부분이 있으면 더 좋을 것 같아요~

2022-05-30 08:54 UTC, LeeJE20 commented on src/routes/auth/authLoginPOST.js
>        return res.status(statusCode.NOT_FOUND).send(util.fail(statusCode.NOT_FOUND, responseMessage.NO_USER));
statusCode가 NOT_FOUND이면 404인데, 이건 보통 존재하지 않는 페이지(라우터)에 접속했을 때 나오는 코드라서 BAD_REQUEST (400) 으로 바꾸면 좋겠어요!

2022-05-30 09:03 UTC, LeeJE20 reviewed
코멘트

2022-05-30 09:03 UTC, LeeJE20 commented on src/routes/auth/signup/signupPOST.js
> +    const loginUser = await userDB.getUserByEmail(client, email);
32번 라인은 유저 아이디를 알기 위해서 있는 라인 맞나요? 
29번 라인의 postUserBySignup에서 마지막 부분에 returning * 하면 id도 불러올 수 있을 것 같은데,, 확실하게는 모르겠네요. 한번 체크해봐도 좋을 것 같아요.

2022-05-30 09:16 UTC, LeeJE20 requested changes
코멘트

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +    onsole.log(`[ERROR] [${req.method.toUpperCase()}] ${req.originalUrl}`, `[CONTENT] ${error}`);
49라인 오타있어요!
console.log의 c가 빠져 있네요.

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +          res.status(401).send({
13라인에서 res.status 앞에 return 안 써도 괜찮나요?

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +            res.status(401).send({
21라인에서 res.status 앞에 return 안 써도 괜찮나요?

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +          res.status(401).send({
덧붙여서 우리가 평소에 하던 것처럼 util 이용해 response 보내는 것으로 수정하면 더 좋을 것 같아요~

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +            res.status(401).send({
덧붙여서 우리가 평소에 하던 것처럼 util 이용해 response 보내는 것으로 수정하면 더 좋을 것 같아요~

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +            res.status(200).send({
우리가 평소에 하던 것처럼 util 이용해 response 보내는 것으로 수정하면 더 좋을 것 같아요~

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +          res.status(400).send({
res.status 앞에 return 안 써도 괜찮나요?
그리고 우리가 평소에 하던 것처럼 util 이용해 response 보내는 것으로 수정하면 더 좋을 것 같아요~

2022-05-30 09:16 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +          res.status(400).send({
우리가 평소에 하던 것처럼 util 이용해 response 보내는 것으로 수정하면 더 좋을 것 같아요~

2022-05-30 14:01 UTC, choiyoorim commented on src/routes/auth/signup/signupPOST.js
> +    const loginUser = await userDB.getUserByEmail(client, email);
returning 부분에 * 대신 id를 추가해서 해결했습니다! 좋은 의견 고맙습니다 ㅎㅎ.ᐟ

2022-06-02 14:15 UTC, LeeJE20 commented on src/routes/auth/signup/signupPOST.js
>      const user = await userDB.postUserBySignup(client, email, name, nickname, password, themePreference);
아 그렇네요 제가 미처 확인 못 했네요 슬랙에서 한번 말해둘게요!

2022-06-02 14:40 UTC, LeeJE20 reviewed
2차 코멘트
제가 코멘트 너무 많이 해서 힘들게 하는 것 같아서 좀 미안하네요. 항상 수고 많아요! 코멘트 꼼꼼하게 읽어주시고 잘 반영해주어서 정말 고마워요~

2022-06-02 14:40 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +            return res.status(statusCode.OK).send(util.success(statusCode.OK, responseMessage.REFRESH_TOKEN_SUCCESS,{ accesstoken: newAccessToken,}));
24번 라인 responseMessage를 보면 '리프레시 토큰 발급 성공'으로 되어 있는데요! 저희 API 문서 보면 access token 발급 성공으로 되어 있고, 실제로 저희가 주는 데이터도 accesstoken이니 명세서대로 하면 더 좋을 것 같아요~

2022-06-02 14:40 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +          return res.status(statusCode.BAD_REQUEST).send(util.fail(statusCode.BAD_REQUEST,responseMessage.BAD_REQUEST));
27번 라인 responseMessage를 NOT_TOKEN_EXPIRED로 바꿔주세요!

2022-06-02 14:40 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +          res.status(statusCode.NO_CONTENT).send(util.fail(statusCode.NO_CONTENT,responseMessage.NULL_VALUE))
30번 라인
NO_CONTENT(204)는 예를 들어 내가 저장한 소품샵을 요청했으나, 신규유저라서 저장한 소품샵이 없어서 보여줄 내용이 없을 때 사용하는 statusCode입니다. 클라이언트 측에서 request도 제대로 보냈고, 서버에서도 문제 없이 잘 동작했으나 보여줄 내용이 없을 때 사용하는 것이지요.

해당 코드는 클라이언트 측에서 필요한 값을 보내지 않아서 생긴 오류이므로, BAD_REQUEST(400)를 쓰는 것이 적절해 보입니다.

2022-06-02 14:40 UTC, LeeJE20 commented on src/routes/auth/signup/signupPOST.js
> +    redisClient.set(String(user[0].id),String(refreshtoken));
코드가 더 깔끔해졌네요 굿!!

2022-06-02 14:45 UTC, LeeJE20 reviewed
2차 코멘트: 리프레시 토큰 쿠키 관련

2022-06-02 14:45 UTC, LeeJE20 commented on src/routes/auth/authLoginPOST.js
> +      return res.status(statusCode.OK).cookie("userId",user[0].id).cookie("refreshToken",refreshtoken).send(util.success(statusCode.OK, responseMessage.LOGIN_SUCCESS, accesstoken));
30번 라인에서 response 보낼 때 쿠키로 refreshToken은 안 보내도 될 것 같아요!
슬랙 내용 참고 부탁드려요!
https://2sodam.slack.com/archives/C02SWV55ZA5/p1654178979242209?thread_ts=1653842851.153909&cid=C02SWV55ZA5

2022-06-02 14:45 UTC, LeeJE20 commented on src/routes/auth/refreshPOST.js
> +        const refreshToken = req.cookies.refreshToken;
리프레시 토큰을 쿠키에서 읽어와서 사용하기 보다는, userId를 이용해 레디스에 저장된 refreshToken 값을 읽어와서 사용하는 식으로 수정하면 좋을 것 같아요!
슬랙 내용 참고해주세요~

https://2sodam.slack.com/archives/C02SWV55ZA5/p1654178979242209?thread_ts=1653842851.153909&cid=C02SWV55ZA5

2022-06-05 21:22 UTC, Nahee-Park requested changes
@choiyoorim 어려운 기능인데 정말 너무너무 고생하셨어요!!! 갓유림,, 폭풍성장한 것 같아여

전체적으로 prettierrc.js가 안 먹혀 있는 것 같은데 혹시 vscode 자체 설정(setting.json)에서 
```
"prettier.requireConfig": true,
"prettier.configPath": ".prettierrc.js",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

이런 내용 설정되어있는지 확인해줄 수 있나요!?
정말 너무 고생했구 저는 리뷰 사항 반영되면 머지해도 좋을 것 같아요!
그 정은언니가 추가적으로 말해준, 리턴값으로 리프레시토큰 보내지 않고 userId만 보내도록 로직 수정하는  것은 반영하면 좋지만 일단 수정하지 않아도 크게 동작 차이가 없을 것 같아서 그 작업으로 인해 리뷰 반영이 늦어진다면 이 피알 머지 후 추후(어쩌면 릴리즈 이후?)에 반영해서 새로 Pr을 날려도 상관 없을 것 같습니다! 일단은 클라 쪽으로 가는 response값에 집중해서 코드 수정하고 빠르게 머지하면 좋을 것 같아요!

2022-06-05 21:22 UTC, Nahee-Park commented on src/lib/jwtHandlers.js
> +    }
저 이 부분에서 sending request가 엄청 지연되고 결과값이 안 오는데 catch(err)로 빠지지도 않아요
```
const data = await getAsync(userId);
```
이 부분에서 데이터가 안 오는 것 같은데 혹시 추정되는 이유가 있나요?

2022-06-05 21:22 UTC, Nahee-Park commented on src/routes/auth/signup/signupPOST.js
>      const user = await userDB.postUserBySignup(client, email, name, nickname, password, themePreference);
@choiyoorim @LeeJE20 이 부분 이 Pr 머지되고 제가 작업해서 올리겠습니다

2022-06-06 07:11 UTC, choiyoorim commented on src/routes/auth/refreshPOST.js
> +            return res.status(statusCode.OK).send(util.success(statusCode.OK, responseMessage.REFRESH_TOKEN_SUCCESS,{ accesstoken: newAccessToken,}));
오 확인했습니다 💗

2022-06-06 07:22 UTC, choiyoorim commented on src/routes/auth/authLoginPOST.js
> +      return res.status(statusCode.OK).cookie("userId",user[0].id).cookie("refreshToken",refreshtoken).send(util.success(statusCode.OK, responseMessage.LOGIN_SUCCESS, accesstoken));
오 확인햇슴다~.ᐟ

2022-06-06 07:34 UTC, choiyoorim commented on src/routes/auth/refreshPOST.js
> +        const refreshToken = req.cookies.refreshToken;
이건... 저번에도 한 번 언급했던 부분이긴 한데, 슬랙(https://2sodam.slack.com/archives/C02SWV55ZA5/p1653520099062669) 이부분을 참고해주시면 좋을 것 같아요!  더 간단히 설명해보자면 jwtHandlers에 refreshVerify 함수 부분을 보면 쿠키에 있는 유저아이디값과 리프레쉬 토큰값을 받아와서, 사용자가 가진 리프레쉬 토큰 값과 우리가 데이터상에 가지고 있는 리프레쉬토큰 값이 같은지 비교하는 과정이 있습니다! 이 과정을 통해서 사용자가 제출한 리프레쉬토큰값이 옳은 값인지 판단하는 거라고 생각하시면 될 것 같습니다! api명세서랑 다른 부분이 있어서 이후 api명세서는 바꿔놓도록 하겠습니다!

2022-06-06 08:20 UTC, choiyoorim commented on src/lib/jwtHandlers.js
> +    }
엇... 어떤 식으로 했더니.. 안나오나요...? postman으로 요청보냈는데 데이터가 안온건가요?

2022-06-06 12:29 UTC, merged