[feat] 어드민 소품샵 데이터 추가 및 수정 기능 추가 #175
TeamSodam/sodam-server pull request #196
Opened 2022-07-09 07:32 UTC by choiyoorim

## ✅ PR check list

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message가 적절한지 확인해주세요.
- [x] 적절한 branch로 요청했는지 확인해주세요.
- [x] Assignees, Label을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.

<br/>

## 📝 PR 요약

- /admin/shop/existshop api 개발 
    - 기존 소품샵 이름을 받아서 소품샵 데이터 수정 가능
    - 모든 데이터 다시 작성해줘야 하는 문제 있음
    - 이는 앞으로 수정 예정.. 
- /admin/shop/newshop api 개발
    - 새로운 소품샵 데이터 받아서 추가 가능  
    - 중복인지 검사해주는 기능 아직 없음 수정 예정..
- 두 api 모두 formdata 통해서만 이미지 추가 가능

- resolved: #175(해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.

<br/>

## 📌 변경 사항 및 주의 사항
- 수정할 부분이 아직 많고 api 명세서 그대로 코드 작성은 안 이루어짐.. 
- api 명세서 update 할 예정
- 이미지 추가시 무조건 formdata 통해서 update
- 이미지 preview 조건은 무조건 배열 첫 번째일 때 프리뷰가 됨

<br/>

2022-08-14 04:04 UTC, Nahee-Park requested changes
리뷰 남긴 거 JSON.parse 관련해서 반영해주세요!

2022-08-14 04:04 UTC, Nahee-Park commented on src/routes/admin/existShopDataPUT.js
> +            if(theme.includes(element.name)){
req.body로 들어온 데이터가 JSON.stringify를 통해 스트링으로 파싱된 데이터라 이걸 JSON.parse로 풀어줘야  제대로 동작할 것 같아요!!

2022-08-14 04:04 UTC, Nahee-Park commented on src/routes/admin/existShopDataPUT.js
> +            if(theme.includes(element.name)){
```suggestion
            if(JSON.parse(theme).includes(element.name)){
```
요런 식으로 해야 "["빈티지","아기자기"]" 으로 들어왔던 데이터가 ["빈티지","아기자기"]로 파싱될 거 같아요!

2022-08-14 04:04 UTC, Nahee-Park commented on src/routes/admin/existShopDataPUT.js
> +            if(category.includes(element.name)){
이쪽도 JSON.parse가 필요할 것 같습미다!

2022-08-14 04:40 UTC, Nahee-Park commented on src/routes/admin/newShopDataPOST.js
> +        if(theme.includes(element.name)){
이쪽도 해주세여!

2022-08-14 04:40 UTC, Nahee-Park commented on src/routes/admin/newShopDataPOST.js
> +      if(category.includes(element.name)){
여기도 !

2022-08-21 09:15 UTC, Nahee-Park approved these changes

2022-08-21 09:24 UTC, Nahee-Park requested changes

2022-08-21 09:24 UTC, Nahee-Park commented on src/routes/admin/newShopDataPOST.js
> +      const createdShopImage = await reviewDB.insertShopImage(client, newShopId, url);
@choiyoorim 
이거 리뷰 디비에 넣는 거 맞나요 ?

2022-08-21 09:26 UTC, Nahee-Park commented on src/routes/admin/newShopDataPOST.js
> +      const createdShopImage = await reviewDB.insertShopImage(client, newShopId, url);
reviewDB가 이 파일에서 선언도 되어있지 않아서요!

2022-08-21 09:31 UTC, choiyoorim commented on src/routes/admin/newShopDataPOST.js
> +      const createdShopImage = await reviewDB.insertShopImage(client, newShopId, url);
아 이부분 잘못들어간 것 같네요! 아마 선언도 안되어있어서 코드 작동 안해서 문제를 발견못한 것 같습니다! 집가서 해당 코드 삭제해둘게요!

2022-08-21 13:43 UTC, Nahee-Park commented on src/routes/admin/newShopDataPOST.js
> +      const createdShopImage = await reviewDB.insertShopImage(client, newShopId, url);
@choiyoorim 네넵 !! 이거 삭제하고 이미지 url 0번째 뿐만 아니라 4개 등록해도 다 들어가도록 수정해주면 좋을 것 같습니다!

2022-09-10 08:38 UTC, Nahee-Park approved these changes
굿굿

2022-09-10 09:07 UTC, merged