[Test] 지역별, 테마별 소품샵 정보 불러오기 테스트코드 작성, 리팩토링
TeamSodam/sodam-server pull request #91
Opened 2022-02-06 12:33 UTC by Nahee-Park

## ✅ PR check list

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message가 적절한지 확인해주세요.
- [x] 적절한 branch로 요청했는지 확인해주세요.
- [x] Assignees, Label을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.

<br/>

## 📝 PR 요약

- [GET] /shop?area={}&sort={} 테스트 코드 작성
    - 인기순 정렬일 때 
    - mysave 정렬일 때 
        - 로그인 안했을 때
        - 로그인 했는데 저장된 소품샵이 없을 때
        - 로그인 했는데 저장된 소품샵이 있을 때 
- [GET] /shop?theme={}&sort={}&offset={}&limit={} 테스트 코드 작성 
    - 인기순 정렬일 때
        - offset, limit 없을 때 `expect(res.body.data).to.have.lengthOf(20)`로 offset=1, limit=20 조건을 디폴트로 해서 총 20개가 들어오는 것을 확인 
        - offset, limit 있을 때 : 배열 길이 점검
    - 리뷰 많은 순 정렬일 때
         - offset, limit 없을 때 `expect(res.body.data).to.have.lengthOf(20)`로 offset=1, limit=20 조건을 디폴트로 해서 총 20개가 들어오는 것을 확인 
        - offset, limit 있을 때 : 배열 길이 점검
- resolved: #90 

<br/>

## 📌 변경 사항 및 주의 사항

<br/>

2022-02-20 10:05 UTC, LeeJE20 requested changes

2022-02-20 10:05 UTC, LeeJE20 commented on __test__/shop.spec.js
> +  it('[GET] 테마별 소품샵 : 인기순 정렬 - offset 1, limit 10', (done) => {
165, 169 라인도 마찬가지

2022-02-20 10:05 UTC, LeeJE20 commented on __test__/shop.spec.js
> +        expect(res.body.data).to.have.lengthOf(10);
155, 177 라인도 마찬가지

2022-02-20 10:18 UTC, LeeJE20 requested changes

2022-02-20 10:18 UTC, LeeJE20 commented on src/routes/shop/shopGET.js
> +  pageOffset = Number((offset - 1) * limit);
offset과 limit에 숫자가 아닌 일반 string이 들어오면 오류가 생길 것 같아요~
17번 라인 위에 offset과 limit이 숫자로 잘 들어왔는지 확인하는 로직이 있으면 더 안전한 코드가 될 수 있을 거예요~

2022-02-20 10:18 UTC, LeeJE20 commented on src/routes/shop/shopGET.js
> +  pageOffset = Number((offset - 1) * limit);
갑자기 생각난건데 음수나 0이 아닌지, 실수가 아닌 정수가 맞는지 확인해보면 좋겠네요!

2022-03-08 20:21 UTC, Nahee-Park commented on __test__/shop.spec.js
> +        expect(res.body.data).to.have.lengthOf(10);
@LeeJE20  이 부분은 아기자기한 테마인 가게가 총 219개, 힘한 테마인 가게가 총 70개임을 알고있어서 현재 이 개수 이내에선 저런 결과가 기대된다는 의미에서 이렇게 작성을 했었습니다! 그런데 전체적으로 저희가 짠 테스트코드들이 db 내부 데이터가 변하면 제대로 테스트되기 어려울 것 같다는 생각이 들어서 (소품샵이 삭제된다거나, 리뷰가 삭제된다거나 등등 ..? ) 이 부분들을 어떻게 정확하게 테스트 할 수 있을지 좀 더 고민해봐야할 것 같아요 ㅠㅠ

2022-03-08 20:37 UTC, merged